// Official CreateSE built-in dataset: 単音ベース 116 (48 kHz / 24-bit / stereo).
window.HITSOUND_CANDIDATES = [
  {
    "id": "SRC001",
    "name": "01.Annihilator 1.wav",
    "originalName": "01.Annihilator 1.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "001",
    "entry": "01.Annihilator 1.wav",
    "globalRank": 1,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC002",
    "name": "01.Annihilator 10.wav",
    "originalName": "01.Annihilator 10.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "002",
    "entry": "01.Annihilator 10.wav",
    "globalRank": 2,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC003",
    "name": "01.Annihilator 2.wav",
    "originalName": "01.Annihilator 2.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "003",
    "entry": "01.Annihilator 2.wav",
    "globalRank": 3,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC004",
    "name": "01.Annihilator 3.wav",
    "originalName": "01.Annihilator 3.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "004",
    "entry": "01.Annihilator 3.wav",
    "globalRank": 4,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC005",
    "name": "01.Annihilator 4.wav",
    "originalName": "01.Annihilator 4.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "005",
    "entry": "01.Annihilator 4.wav",
    "globalRank": 5,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC006",
    "name": "01.Annihilator 5.wav",
    "originalName": "01.Annihilator 5.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "006",
    "entry": "01.Annihilator 5.wav",
    "globalRank": 6,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC007",
    "name": "01.Annihilator 6.wav",
    "originalName": "01.Annihilator 6.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "007",
    "entry": "01.Annihilator 6.wav",
    "globalRank": 7,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC008",
    "name": "01.Annihilator 7.wav",
    "originalName": "01.Annihilator 7.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "008",
    "entry": "01.Annihilator 7.wav",
    "globalRank": 8,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC009",
    "name": "01.Annihilator 8.wav",
    "originalName": "01.Annihilator 8.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "009",
    "entry": "01.Annihilator 8.wav",
    "globalRank": 9,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC010",
    "name": "01.Annihilator 9.wav",
    "originalName": "01.Annihilator 9.wav",
    "family": "Annihilator",
    "originalFamily": "Annihilator",
    "sourceNumber": "010",
    "entry": "01.Annihilator 9.wav",
    "globalRank": 10,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC011",
    "name": "02.Doom Pulse 1.wav",
    "originalName": "02.Doom Pulse 1.wav",
    "family": "Doom Pulse",
    "originalFamily": "Doom Pulse",
    "sourceNumber": "011",
    "entry": "02.Doom Pulse 1.wav",
    "globalRank": 11,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC012",
    "name": "02.Doom Pulse 10.wav",
    "originalName": "02.Doom Pulse 10.wav",
    "family": "Doom Pulse",
    "originalFamily": "Doom Pulse",
    "sourceNumber": "012",
    "entry": "02.Doom Pulse 10.wav",
    "globalRank": 12,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC013",
    "name": "02.Doom Pulse 2.wav",
    "originalName": "02.Doom Pulse 2.wav",
    "family": "Doom Pulse",
    "originalFamily": "Doom Pulse",
    "sourceNumber": "013",
    "entry": "02.Doom Pulse 2.wav",
    "globalRank": 13,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC014",
    "name": "02.Doom Pulse 9.wav",
    "originalName": "02.Doom Pulse 9.wav",
    "family": "Doom Pulse",
    "originalFamily": "Doom Pulse",
    "sourceNumber": "014",
    "entry": "02.Doom Pulse 9.wav",
    "globalRank": 14,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC015",
    "name": "BD1.wav",
    "originalName": "BD1.wav",
    "family": "Bass Drum / Kick",
    "originalFamily": "Bass Drum / Kick",
    "sourceNumber": "015",
    "entry": "BD1.wav",
    "globalRank": 15,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC016",
    "name": "BD3.wav",
    "originalName": "BD3.wav",
    "family": "Bass Drum / Kick",
    "originalFamily": "Bass Drum / Kick",
    "sourceNumber": "016",
    "entry": "BD3.wav",
    "globalRank": 16,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC017",
    "name": "BD4.wav",
    "originalName": "BD4.wav",
    "family": "Bass Drum / Kick",
    "originalFamily": "Bass Drum / Kick",
    "sourceNumber": "017",
    "entry": "BD4.wav",
    "globalRank": 17,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC018",
    "name": "CLAP2.wav",
    "originalName": "CLAP2.wav",
    "family": "Clap",
    "originalFamily": "Clap",
    "sourceNumber": "018",
    "entry": "CLAP2.wav",
    "globalRank": 18,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC019",
    "name": "Clave 01.wav",
    "originalName": "Clave 01.wav",
    "family": "Clave / Claves",
    "originalFamily": "Clave / Claves",
    "sourceNumber": "019",
    "entry": "Clave 01.wav",
    "globalRank": 19,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC020",
    "name": "Clave 02.wav",
    "originalName": "Clave 02.wav",
    "family": "Clave / Claves",
    "originalFamily": "Clave / Claves",
    "sourceNumber": "020",
    "entry": "Clave 02.wav",
    "globalRank": 20,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC021",
    "name": "Clave 03.wav",
    "originalName": "Clave 03.wav",
    "family": "Clave / Claves",
    "originalFamily": "Clave / Claves",
    "sourceNumber": "021",
    "entry": "Clave 03.wav",
    "globalRank": 21,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC022",
    "name": "Clave 04.wav",
    "originalName": "Clave 04.wav",
    "family": "Clave / Claves",
    "originalFamily": "Clave / Claves",
    "sourceNumber": "022",
    "entry": "Clave 04.wav",
    "globalRank": 22,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC023",
    "name": "ForestPerc_ProcessA_Hit_02.wav",
    "originalName": "ForestPerc_ProcessA_Hit_02.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "023",
    "entry": "ForestPerc_ProcessA_Hit_02.wav",
    "globalRank": 23,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC024",
    "name": "ForestPerc_ProcessA_Hit_03.wav",
    "originalName": "ForestPerc_ProcessA_Hit_03.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "024",
    "entry": "ForestPerc_ProcessA_Hit_03.wav",
    "globalRank": 24,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC025",
    "name": "ForestPerc_ProcessA_Hit_04.wav",
    "originalName": "ForestPerc_ProcessA_Hit_04.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "025",
    "entry": "ForestPerc_ProcessA_Hit_04.wav",
    "globalRank": 25,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC026",
    "name": "ForestPerc_ProcessA_Hit_05.wav",
    "originalName": "ForestPerc_ProcessA_Hit_05.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "026",
    "entry": "ForestPerc_ProcessA_Hit_05.wav",
    "globalRank": 26,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC027",
    "name": "ForestPerc_ProcessA_Hit_06.wav",
    "originalName": "ForestPerc_ProcessA_Hit_06.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "027",
    "entry": "ForestPerc_ProcessA_Hit_06.wav",
    "globalRank": 27,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC028",
    "name": "ForestPerc_ProcessA_Hit_07.wav",
    "originalName": "ForestPerc_ProcessA_Hit_07.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "028",
    "entry": "ForestPerc_ProcessA_Hit_07.wav",
    "globalRank": 28,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC029",
    "name": "ForestPerc_ProcessA_Hit_08.wav",
    "originalName": "ForestPerc_ProcessA_Hit_08.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "029",
    "entry": "ForestPerc_ProcessA_Hit_08.wav",
    "globalRank": 29,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC030",
    "name": "ForestPerc_ProcessA_Hit_09.wav",
    "originalName": "ForestPerc_ProcessA_Hit_09.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "030",
    "entry": "ForestPerc_ProcessA_Hit_09.wav",
    "globalRank": 30,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC031",
    "name": "ForestPerc_ProcessA_Hit_10.wav",
    "originalName": "ForestPerc_ProcessA_Hit_10.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "031",
    "entry": "ForestPerc_ProcessA_Hit_10.wav",
    "globalRank": 31,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC032",
    "name": "ForestPerc_ProcessA_Hit_11.wav",
    "originalName": "ForestPerc_ProcessA_Hit_11.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "032",
    "entry": "ForestPerc_ProcessA_Hit_11.wav",
    "globalRank": 32,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC033",
    "name": "ForestPerc_ProcessA_Hit_12.wav",
    "originalName": "ForestPerc_ProcessA_Hit_12.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "033",
    "entry": "ForestPerc_ProcessA_Hit_12.wav",
    "globalRank": 33,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC034",
    "name": "ForestPerc_ProcessA_Hit_13.wav",
    "originalName": "ForestPerc_ProcessA_Hit_13.wav",
    "family": "Forest Perc A",
    "originalFamily": "Forest Perc A",
    "sourceNumber": "034",
    "entry": "ForestPerc_ProcessA_Hit_13.wav",
    "globalRank": 34,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC035",
    "name": "ForestPerc_ProcessB_Hit_02.wav",
    "originalName": "ForestPerc_ProcessB_Hit_02.wav",
    "family": "Forest Perc B",
    "originalFamily": "Forest Perc B",
    "sourceNumber": "035",
    "entry": "ForestPerc_ProcessB_Hit_02.wav",
    "globalRank": 35,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC036",
    "name": "ForestPerc_ProcessB_Hit_04.wav",
    "originalName": "ForestPerc_ProcessB_Hit_04.wav",
    "family": "Forest Perc B",
    "originalFamily": "Forest Perc B",
    "sourceNumber": "036",
    "entry": "ForestPerc_ProcessB_Hit_04.wav",
    "globalRank": 36,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC037",
    "name": "ForestPerc_ProcessB_Hit_05.wav",
    "originalName": "ForestPerc_ProcessB_Hit_05.wav",
    "family": "Forest Perc B",
    "originalFamily": "Forest Perc B",
    "sourceNumber": "037",
    "entry": "ForestPerc_ProcessB_Hit_05.wav",
    "globalRank": 37,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC038",
    "name": "ForestPerc_ProcessB_Hit_06.wav",
    "originalName": "ForestPerc_ProcessB_Hit_06.wav",
    "family": "Forest Perc B",
    "originalFamily": "Forest Perc B",
    "sourceNumber": "038",
    "entry": "ForestPerc_ProcessB_Hit_06.wav",
    "globalRank": 38,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC039",
    "name": "ForestPerc_ProcessB_Hit_07.wav",
    "originalName": "ForestPerc_ProcessB_Hit_07.wav",
    "family": "Forest Perc B",
    "originalFamily": "Forest Perc B",
    "sourceNumber": "039",
    "entry": "ForestPerc_ProcessB_Hit_07.wav",
    "globalRank": 39,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC040",
    "name": "ForestPerc_ProcessB_Hit_08.wav",
    "originalName": "ForestPerc_ProcessB_Hit_08.wav",
    "family": "Forest Perc B",
    "originalFamily": "Forest Perc B",
    "sourceNumber": "040",
    "entry": "ForestPerc_ProcessB_Hit_08.wav",
    "globalRank": 40,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC041",
    "name": "ForestPerc_ProcessB_Hit_09.wav",
    "originalName": "ForestPerc_ProcessB_Hit_09.wav",
    "family": "Forest Perc B",
    "originalFamily": "Forest Perc B",
    "sourceNumber": "041",
    "entry": "ForestPerc_ProcessB_Hit_09.wav",
    "globalRank": 41,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC042",
    "name": "ForestPerc_ProcessB_Hit_10.wav",
    "originalName": "ForestPerc_ProcessB_Hit_10.wav",
    "family": "Forest Perc B",
    "originalFamily": "Forest Perc B",
    "sourceNumber": "042",
    "entry": "ForestPerc_ProcessB_Hit_10.wav",
    "globalRank": 42,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC043",
    "name": "ForestPerc_ProcessC_Hit_01.wav",
    "originalName": "ForestPerc_ProcessC_Hit_01.wav",
    "family": "Forest Perc C",
    "originalFamily": "Forest Perc C",
    "sourceNumber": "043",
    "entry": "ForestPerc_ProcessC_Hit_01.wav",
    "globalRank": 43,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC044",
    "name": "ForestPerc_ProcessC_Hit_02.wav",
    "originalName": "ForestPerc_ProcessC_Hit_02.wav",
    "family": "Forest Perc C",
    "originalFamily": "Forest Perc C",
    "sourceNumber": "044",
    "entry": "ForestPerc_ProcessC_Hit_02.wav",
    "globalRank": 44,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC045",
    "name": "ForestPerc_ProcessC_Hit_03.wav",
    "originalName": "ForestPerc_ProcessC_Hit_03.wav",
    "family": "Forest Perc C",
    "originalFamily": "Forest Perc C",
    "sourceNumber": "045",
    "entry": "ForestPerc_ProcessC_Hit_03.wav",
    "globalRank": 45,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC046",
    "name": "ForestPerc_ProcessC_Hit_04.wav",
    "originalName": "ForestPerc_ProcessC_Hit_04.wav",
    "family": "Forest Perc C",
    "originalFamily": "Forest Perc C",
    "sourceNumber": "046",
    "entry": "ForestPerc_ProcessC_Hit_04.wav",
    "globalRank": 46,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC047",
    "name": "ForestPerc_ProcessC_Hit_05.wav",
    "originalName": "ForestPerc_ProcessC_Hit_05.wav",
    "family": "Forest Perc C",
    "originalFamily": "Forest Perc C",
    "sourceNumber": "047",
    "entry": "ForestPerc_ProcessC_Hit_05.wav",
    "globalRank": 47,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC048",
    "name": "ForestPerc_ProcessC_Hit_06.wav",
    "originalName": "ForestPerc_ProcessC_Hit_06.wav",
    "family": "Forest Perc C",
    "originalFamily": "Forest Perc C",
    "sourceNumber": "048",
    "entry": "ForestPerc_ProcessC_Hit_06.wav",
    "globalRank": 48,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC049",
    "name": "ForestPerc_ProcessC_Hit_07.wav",
    "originalName": "ForestPerc_ProcessC_Hit_07.wav",
    "family": "Forest Perc C",
    "originalFamily": "Forest Perc C",
    "sourceNumber": "049",
    "entry": "ForestPerc_ProcessC_Hit_07.wav",
    "globalRank": 49,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC050",
    "name": "ForestPerc_ProcessD_Hit_01.wav",
    "originalName": "ForestPerc_ProcessD_Hit_01.wav",
    "family": "Forest Perc D",
    "originalFamily": "Forest Perc D",
    "sourceNumber": "050",
    "entry": "ForestPerc_ProcessD_Hit_01.wav",
    "globalRank": 50,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC051",
    "name": "ForestPerc_ProcessD_Hit_02.wav",
    "originalName": "ForestPerc_ProcessD_Hit_02.wav",
    "family": "Forest Perc D",
    "originalFamily": "Forest Perc D",
    "sourceNumber": "051",
    "entry": "ForestPerc_ProcessD_Hit_02.wav",
    "globalRank": 51,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC052",
    "name": "ForestPerc_ProcessD_Hit_03.wav",
    "originalName": "ForestPerc_ProcessD_Hit_03.wav",
    "family": "Forest Perc D",
    "originalFamily": "Forest Perc D",
    "sourceNumber": "052",
    "entry": "ForestPerc_ProcessD_Hit_03.wav",
    "globalRank": 52,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC053",
    "name": "ForestPerc_ProcessD_Hit_04.wav",
    "originalName": "ForestPerc_ProcessD_Hit_04.wav",
    "family": "Forest Perc D",
    "originalFamily": "Forest Perc D",
    "sourceNumber": "053",
    "entry": "ForestPerc_ProcessD_Hit_04.wav",
    "globalRank": 53,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC054",
    "name": "ForestPerc_ProcessE_Hit_01.wav",
    "originalName": "ForestPerc_ProcessE_Hit_01.wav",
    "family": "Forest Perc E",
    "originalFamily": "Forest Perc E",
    "sourceNumber": "054",
    "entry": "ForestPerc_ProcessE_Hit_01.wav",
    "globalRank": 54,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC055",
    "name": "ForestPerc_ProcessE_Hit_02.wav",
    "originalName": "ForestPerc_ProcessE_Hit_02.wav",
    "family": "Forest Perc E",
    "originalFamily": "Forest Perc E",
    "sourceNumber": "055",
    "entry": "ForestPerc_ProcessE_Hit_02.wav",
    "globalRank": 55,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC056",
    "name": "ForestPerc_ProcessE_Hit_04.wav",
    "originalName": "ForestPerc_ProcessE_Hit_04.wav",
    "family": "Forest Perc E",
    "originalFamily": "Forest Perc E",
    "sourceNumber": "056",
    "entry": "ForestPerc_ProcessE_Hit_04.wav",
    "globalRank": 56,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC057",
    "name": "ForestPerc_ProcessF_Hit_02.wav",
    "originalName": "ForestPerc_ProcessF_Hit_02.wav",
    "family": "Forest Perc F",
    "originalFamily": "Forest Perc F",
    "sourceNumber": "057",
    "entry": "ForestPerc_ProcessF_Hit_02.wav",
    "globalRank": 57,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC058",
    "name": "ForestPerc_ProcessF_Hit_04.wav",
    "originalName": "ForestPerc_ProcessF_Hit_04.wav",
    "family": "Forest Perc F",
    "originalFamily": "Forest Perc F",
    "sourceNumber": "058",
    "entry": "ForestPerc_ProcessF_Hit_04.wav",
    "globalRank": 58,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC059",
    "name": "ForestPerc_ProcessF_Hit_06.wav",
    "originalName": "ForestPerc_ProcessF_Hit_06.wav",
    "family": "Forest Perc F",
    "originalFamily": "Forest Perc F",
    "sourceNumber": "059",
    "entry": "ForestPerc_ProcessF_Hit_06.wav",
    "globalRank": 59,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC060",
    "name": "ForestPerc_ProcessF_Hit_07.wav",
    "originalName": "ForestPerc_ProcessF_Hit_07.wav",
    "family": "Forest Perc F",
    "originalFamily": "Forest Perc F",
    "sourceNumber": "060",
    "entry": "ForestPerc_ProcessF_Hit_07.wav",
    "globalRank": 60,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC061",
    "name": "ForestPerc_ProcessF_Hit_08.wav",
    "originalName": "ForestPerc_ProcessF_Hit_08.wav",
    "family": "Forest Perc F",
    "originalFamily": "Forest Perc F",
    "sourceNumber": "061",
    "entry": "ForestPerc_ProcessF_Hit_08.wav",
    "globalRank": 61,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC062",
    "name": "HH1.wav",
    "originalName": "HH1.wav",
    "family": "Hi-Hat",
    "originalFamily": "Hi-Hat",
    "sourceNumber": "062",
    "entry": "HH1.wav",
    "globalRank": 62,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC063",
    "name": "HH2.wav",
    "originalName": "HH2.wav",
    "family": "Hi-Hat",
    "originalFamily": "Hi-Hat",
    "sourceNumber": "063",
    "entry": "HH2.wav",
    "globalRank": 63,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC064",
    "name": "HH4.wav",
    "originalName": "HH4.wav",
    "family": "Hi-Hat",
    "originalFamily": "Hi-Hat",
    "sourceNumber": "064",
    "entry": "HH4.wav",
    "globalRank": 64,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC065",
    "name": "HH5.wav",
    "originalName": "HH5.wav",
    "family": "Hi-Hat",
    "originalFamily": "Hi-Hat",
    "sourceNumber": "065",
    "entry": "HH5.wav",
    "globalRank": 65,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC066",
    "name": "Rimshot 02.wav",
    "originalName": "Rimshot 02.wav",
    "family": "Rimshot",
    "originalFamily": "Rimshot",
    "sourceNumber": "066",
    "entry": "Rimshot 02.wav",
    "globalRank": 66,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC067",
    "name": "Rimshot 04.wav",
    "originalName": "Rimshot 04.wav",
    "family": "Rimshot",
    "originalFamily": "Rimshot",
    "sourceNumber": "067",
    "entry": "Rimshot 04.wav",
    "globalRank": 67,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC068",
    "name": "Rimshot 18.wav",
    "originalName": "Rimshot 18.wav",
    "family": "Rimshot",
    "originalFamily": "Rimshot",
    "sourceNumber": "068",
    "entry": "Rimshot 18.wav",
    "globalRank": 68,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC069",
    "name": "Rimshot 22.wav",
    "originalName": "Rimshot 22.wav",
    "family": "Rimshot",
    "originalFamily": "Rimshot",
    "sourceNumber": "069",
    "entry": "Rimshot 22.wav",
    "globalRank": 69,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC070",
    "name": "Rimshot 25.wav",
    "originalName": "Rimshot 25.wav",
    "family": "Rimshot",
    "originalFamily": "Rimshot",
    "sourceNumber": "070",
    "entry": "Rimshot 25.wav",
    "globalRank": 70,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC071",
    "name": "Rimshot 35.wav",
    "originalName": "Rimshot 35.wav",
    "family": "Rimshot",
    "originalFamily": "Rimshot",
    "sourceNumber": "071",
    "entry": "Rimshot 35.wav",
    "globalRank": 71,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC072",
    "name": "Rimshot 36.wav",
    "originalName": "Rimshot 36.wav",
    "family": "Rimshot",
    "originalFamily": "Rimshot",
    "sourceNumber": "072",
    "entry": "Rimshot 36.wav",
    "globalRank": 72,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC073",
    "name": "Rimshot 37.wav",
    "originalName": "Rimshot 37.wav",
    "family": "Rimshot",
    "originalFamily": "Rimshot",
    "sourceNumber": "073",
    "entry": "Rimshot 37.wav",
    "globalRank": 73,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC074",
    "name": "RnT_Agogo-01.wav",
    "originalName": "RnT_Agogo-01.wav",
    "family": "Agogo",
    "originalFamily": "Agogo",
    "sourceNumber": "074",
    "entry": "RnT_Agogo-01.wav",
    "globalRank": 74,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC075",
    "name": "RnT_Agogo-02.wav",
    "originalName": "RnT_Agogo-02.wav",
    "family": "Agogo",
    "originalFamily": "Agogo",
    "sourceNumber": "075",
    "entry": "RnT_Agogo-02.wav",
    "globalRank": 75,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC076",
    "name": "RnT_Agogo-03.wav",
    "originalName": "RnT_Agogo-03.wav",
    "family": "Agogo",
    "originalFamily": "Agogo",
    "sourceNumber": "076",
    "entry": "RnT_Agogo-03.wav",
    "globalRank": 76,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC077",
    "name": "RnT_Agogo-04.wav",
    "originalName": "RnT_Agogo-04.wav",
    "family": "Agogo",
    "originalFamily": "Agogo",
    "sourceNumber": "077",
    "entry": "RnT_Agogo-04.wav",
    "globalRank": 77,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC078",
    "name": "RnT_Agogo-05.wav",
    "originalName": "RnT_Agogo-05.wav",
    "family": "Agogo",
    "originalFamily": "Agogo",
    "sourceNumber": "078",
    "entry": "RnT_Agogo-05.wav",
    "globalRank": 78,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC079",
    "name": "RnT_Agogo-06.wav",
    "originalName": "RnT_Agogo-06.wav",
    "family": "Agogo",
    "originalFamily": "Agogo",
    "sourceNumber": "079",
    "entry": "RnT_Agogo-06.wav",
    "globalRank": 79,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC080",
    "name": "RnT_Agogo-07.wav",
    "originalName": "RnT_Agogo-07.wav",
    "family": "Agogo",
    "originalFamily": "Agogo",
    "sourceNumber": "080",
    "entry": "RnT_Agogo-07.wav",
    "globalRank": 80,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC081",
    "name": "RnT_Claves-01.wav",
    "originalName": "RnT_Claves-01.wav",
    "family": "Clave / Claves",
    "originalFamily": "Clave / Claves",
    "sourceNumber": "081",
    "entry": "RnT_Claves-01.wav",
    "globalRank": 81,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC082",
    "name": "RnT_Claves-02.wav",
    "originalName": "RnT_Claves-02.wav",
    "family": "Clave / Claves",
    "originalFamily": "Clave / Claves",
    "sourceNumber": "082",
    "entry": "RnT_Claves-02.wav",
    "globalRank": 82,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC083",
    "name": "RnT_Claves-03.wav",
    "originalName": "RnT_Claves-03.wav",
    "family": "Clave / Claves",
    "originalFamily": "Clave / Claves",
    "sourceNumber": "083",
    "entry": "RnT_Claves-03.wav",
    "globalRank": 83,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC084",
    "name": "RnT_Claves-04.wav",
    "originalName": "RnT_Claves-04.wav",
    "family": "Clave / Claves",
    "originalFamily": "Clave / Claves",
    "sourceNumber": "084",
    "entry": "RnT_Claves-04.wav",
    "globalRank": 84,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC085",
    "name": "RnT_Claves-05.wav",
    "originalName": "RnT_Claves-05.wav",
    "family": "Clave / Claves",
    "originalFamily": "Clave / Claves",
    "sourceNumber": "085",
    "entry": "RnT_Claves-05.wav",
    "globalRank": 85,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC086",
    "name": "RnT_Cowbell-01.wav",
    "originalName": "RnT_Cowbell-01.wav",
    "family": "Cowbell",
    "originalFamily": "Cowbell",
    "sourceNumber": "086",
    "entry": "RnT_Cowbell-01.wav",
    "globalRank": 86,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC087",
    "name": "RnT_Cowbell-02.wav",
    "originalName": "RnT_Cowbell-02.wav",
    "family": "Cowbell",
    "originalFamily": "Cowbell",
    "sourceNumber": "087",
    "entry": "RnT_Cowbell-02.wav",
    "globalRank": 87,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC088",
    "name": "RnT_Cowbell-03.wav",
    "originalName": "RnT_Cowbell-03.wav",
    "family": "Cowbell",
    "originalFamily": "Cowbell",
    "sourceNumber": "088",
    "entry": "RnT_Cowbell-03.wav",
    "globalRank": 88,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC089",
    "name": "RnT_Cowbell-04.wav",
    "originalName": "RnT_Cowbell-04.wav",
    "family": "Cowbell",
    "originalFamily": "Cowbell",
    "sourceNumber": "089",
    "entry": "RnT_Cowbell-04.wav",
    "globalRank": 89,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC090",
    "name": "RnT_Cowbell-05.wav",
    "originalName": "RnT_Cowbell-05.wav",
    "family": "Cowbell",
    "originalFamily": "Cowbell",
    "sourceNumber": "090",
    "entry": "RnT_Cowbell-05.wav",
    "globalRank": 90,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC091",
    "name": "RnT_Cowbell-06.wav",
    "originalName": "RnT_Cowbell-06.wav",
    "family": "Cowbell",
    "originalFamily": "Cowbell",
    "sourceNumber": "091",
    "entry": "RnT_Cowbell-06.wav",
    "globalRank": 91,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC092",
    "name": "RnT_Timbale-01.wav",
    "originalName": "RnT_Timbale-01.wav",
    "family": "Timbale",
    "originalFamily": "Timbale",
    "sourceNumber": "092",
    "entry": "RnT_Timbale-01.wav",
    "globalRank": 92,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC093",
    "name": "RnT_Timbale-02.wav",
    "originalName": "RnT_Timbale-02.wav",
    "family": "Timbale",
    "originalFamily": "Timbale",
    "sourceNumber": "093",
    "entry": "RnT_Timbale-02.wav",
    "globalRank": 93,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC094",
    "name": "RnT_Timbale-03.wav",
    "originalName": "RnT_Timbale-03.wav",
    "family": "Timbale",
    "originalFamily": "Timbale",
    "sourceNumber": "094",
    "entry": "RnT_Timbale-03.wav",
    "globalRank": 94,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC095",
    "name": "RnT_Timbale-04.wav",
    "originalName": "RnT_Timbale-04.wav",
    "family": "Timbale",
    "originalFamily": "Timbale",
    "sourceNumber": "095",
    "entry": "RnT_Timbale-04.wav",
    "globalRank": 95,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC096",
    "name": "RnT_Timbale-05.wav",
    "originalName": "RnT_Timbale-05.wav",
    "family": "Timbale",
    "originalFamily": "Timbale",
    "sourceNumber": "096",
    "entry": "RnT_Timbale-05.wav",
    "globalRank": 96,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC097",
    "name": "RnT_Timbale-06.wav",
    "originalName": "RnT_Timbale-06.wav",
    "family": "Timbale",
    "originalFamily": "Timbale",
    "sourceNumber": "097",
    "entry": "RnT_Timbale-06.wav",
    "globalRank": 97,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC098",
    "name": "RnT_Woodblock-01.wav",
    "originalName": "RnT_Woodblock-01.wav",
    "family": "Woodblock",
    "originalFamily": "Woodblock",
    "sourceNumber": "098",
    "entry": "RnT_Woodblock-01.wav",
    "globalRank": 98,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC099",
    "name": "RnT_Woodblock-02.wav",
    "originalName": "RnT_Woodblock-02.wav",
    "family": "Woodblock",
    "originalFamily": "Woodblock",
    "sourceNumber": "099",
    "entry": "RnT_Woodblock-02.wav",
    "globalRank": 99,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC100",
    "name": "RnT_Woodblock-03.wav",
    "originalName": "RnT_Woodblock-03.wav",
    "family": "Woodblock",
    "originalFamily": "Woodblock",
    "sourceNumber": "100",
    "entry": "RnT_Woodblock-03.wav",
    "globalRank": 100,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC101",
    "name": "SNAP1.wav",
    "originalName": "SNAP1.wav",
    "family": "Snap",
    "originalFamily": "Snap",
    "sourceNumber": "101",
    "entry": "SNAP1.wav",
    "globalRank": 101,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC102",
    "name": "SNAP2.wav",
    "originalName": "SNAP2.wav",
    "family": "Snap",
    "originalFamily": "Snap",
    "sourceNumber": "102",
    "entry": "SNAP2.wav",
    "globalRank": 102,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC103",
    "name": "SNAP3.wav",
    "originalName": "SNAP3.wav",
    "family": "Snap",
    "originalFamily": "Snap",
    "sourceNumber": "103",
    "entry": "SNAP3.wav",
    "globalRank": 103,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC104",
    "name": "SNAP4.wav",
    "originalName": "SNAP4.wav",
    "family": "Snap",
    "originalFamily": "Snap",
    "sourceNumber": "104",
    "entry": "SNAP4.wav",
    "globalRank": 104,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC105",
    "name": "SNARE5.wav",
    "originalName": "SNARE5.wav",
    "family": "Snare",
    "originalFamily": "Snare",
    "sourceNumber": "105",
    "entry": "SNARE5.wav",
    "globalRank": 105,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC106",
    "name": "SNARE6.wav",
    "originalName": "SNARE6.wav",
    "family": "Snare",
    "originalFamily": "Snare",
    "sourceNumber": "106",
    "entry": "SNARE6.wav",
    "globalRank": 106,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC107",
    "name": "Snap 03.wav",
    "originalName": "Snap 03.wav",
    "family": "Snap",
    "originalFamily": "Snap",
    "sourceNumber": "107",
    "entry": "Snap 03.wav",
    "globalRank": 107,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC108",
    "name": "Snap 04.wav",
    "originalName": "Snap 04.wav",
    "family": "Snap",
    "originalFamily": "Snap",
    "sourceNumber": "108",
    "entry": "Snap 04.wav",
    "globalRank": 108,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC109",
    "name": "Snap 05.wav",
    "originalName": "Snap 05.wav",
    "family": "Snap",
    "originalFamily": "Snap",
    "sourceNumber": "109",
    "entry": "Snap 05.wav",
    "globalRank": 109,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC110",
    "name": "TOM1.wav",
    "originalName": "TOM1.wav",
    "family": "Tom",
    "originalFamily": "Tom",
    "sourceNumber": "110",
    "entry": "TOM1.wav",
    "globalRank": 110,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC111",
    "name": "TOM2.wav",
    "originalName": "TOM2.wav",
    "family": "Tom",
    "originalFamily": "Tom",
    "sourceNumber": "111",
    "entry": "TOM2.wav",
    "globalRank": 111,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC112",
    "name": "TOM3.wav",
    "originalName": "TOM3.wav",
    "family": "Tom",
    "originalFamily": "Tom",
    "sourceNumber": "112",
    "entry": "TOM3.wav",
    "globalRank": 112,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC113",
    "name": "TOM4.wav",
    "originalName": "TOM4.wav",
    "family": "Tom",
    "originalFamily": "Tom",
    "sourceNumber": "113",
    "entry": "TOM4.wav",
    "globalRank": 113,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC114",
    "name": "TOM5.wav",
    "originalName": "TOM5.wav",
    "family": "Tom",
    "originalFamily": "Tom",
    "sourceNumber": "114",
    "entry": "TOM5.wav",
    "globalRank": 114,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC115",
    "name": "TOM6.wav",
    "originalName": "TOM6.wav",
    "family": "Tom",
    "originalFamily": "Tom",
    "sourceNumber": "115",
    "entry": "TOM6.wav",
    "globalRank": 115,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  },
  {
    "id": "SRC116",
    "name": "taiko-normal-hitnormal.wav",
    "originalName": "taiko-normal-hitnormal.wav",
    "family": "Taiko Reference",
    "originalFamily": "Taiko Reference",
    "sourceNumber": "116",
    "entry": "taiko-normal-hitnormal.wav",
    "globalRank": 116,
    "userLabel": "",
    "excluded": false,
    "dataset": "single-base-116"
  }
];
